import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import CartProvider from "@/components/Providers";
import ShoppingCart from "@/components/ShoppingCart";
import DrawerCart from "@/components/Drawer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Framz",
  description: "Generated by ayushsonone07",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Navbar/>
          <ShoppingCart/>
          {/* <DrawerCart/> */}
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
